load("@rules_rust//rust:defs.bzl", "rust_doc_test", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "illicit",
    # FIXME translate this metadata somehow
    # description = "An implicit thread-local environment which is indexed by type."
    # categories = ["rust-patterns"]
    # keywords = ["context", "environment", "global", "singleton"]
    # readme = "CHANGELOG.md"
    srcs = glob(["src/**/*.rs"]),
    edition = "2018",
    lint_config = "//:library_lints",
    proc_macro_deps = [
        "//illicit/macro:illicit-macro",
    ],
    version = "1.1.2",
    deps = [
        "@crates//:owning_ref",
        "@crates//:scopeguard",
    ],
)

rust_test(
    name = "illicit_unit_tests",
    crate = "illicit",
)

rust_doc_test(
    name = "illicit_doc_tests",
    crate = "illicit",
)
