load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "illicit",
    # FIXME translate this metadata somehow
    # description = "An implicit thread-local environment which is indexed by type."
    # categories = ["rust-patterns"]
    # keywords = ["context", "environment", "global", "singleton"]
    # readme = "CHANGELOG.md"
    srcs = [
        "src/anon_rc.rs",
        "src/lib.rs",
    ],
    edition = "2018",
    lint_config = "//:library_lints",
    proc_macro_deps = [
        "//illicit/macro:illicit-macro",
    ],
    version = "1.1.2",
    deps = [
        "@crates//:owning_ref",
        "@crates//:scopeguard",
    ],
)

rust_test(
    name = "illicit_unit_tests",
    crate = "illicit",
)

test_suite(
    name = "tests",
    tests = [
        ":illicit_unit_tests",
        "//illicit/benches",
        "//illicit/macro:tests",
    ],
)
