[package]
name = "illicit"
version = "0.10.0-pre"
edition = "2018"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Type-indexed dynamically-scoped singletons."
repository = "https://github.com/anp/moxie"

[dependencies]
illicit-macro = { path = "macro", version = "0.10.0-pre"}
owning_ref = "0.4"
scopeguard = "1"

[dev-dependencies]
assert-panic = "1.0.1"
criterion = "0.3"

[[bench]]
name = "basic_env"
harness = false
