load("@rules_rust//rust:defs.bzl", "rust_shared_library")
load("@rules_rust_wasm_bindgen//:defs.bzl", "rust_wasm_bindgen", "rust_wasm_bindgen_test")

package(default_visibility = ["//visibility:public"])

rust_shared_library(
    name = "raf",
    # FIXME translate this metadata somehow
    # description = "browser event loop scheduler using requestAnimationFrame"
    # categories = ["asynchronous", "concurrency", "gui", "wasm", "web-programming"]
    # keywords = ["scheduler", "events", "requestAnimationFrame"]
    # readme = "CHANGELOG.md"
    srcs = [
        "src/lib.rs",
    ],
    edition = "2018",
    lint_config = "//:library_lints_allowing_unsafe",
    version = "0.2.0-pre",
    deps = [
        "@crates//:futures",
        "@crates//:wasm-bindgen",
        "@crates//:web-sys",
    ],
)

rust_wasm_bindgen(
    name = "raf_wasm_bindgen",
    target = "web",
    wasm_file = ":raf",
)

rust_wasm_bindgen_test(
    name = "raf_wasm_bindgen_unit_tests",
    wasm = "raf_wasm_bindgen",
)
