[package]
name = "honk-vscode"
description = "an awful billed system's vscode extension"
version = "0.1.0-pre"
publish = false
edition = "2018"
license-file = "../../../../LICENSE-MIT"
repository = "https://github.com/anp/moxie.git"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
code-sys = { path = "sys", version = "0.1.0-pre" }
console_error_panic_hook = "0.1.6"
moxie-dom = { path = "../../../dom" }
tracing = { version = "^0.1", features = [ "log" ] }
tracing-wasm = "0.1.0"
wasm-bindgen = "0.2"

[dev-dependencies]
pretty_assertions = "0.6"
wasm-bindgen-test = "0.3"
