strategy:
  matrix:
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
- script: rustup component add rustfmt clippy
- script: rustup target add wasm32-unknown-unknown
- script: cargo install cargo-script
- script: cargo fmt -- --check
- script: cargo fmt-scripts --check
- script: cargo test-core
- script: cargo check-dom-lib
- script: cargo build-dom-hacking
- script: cargo build-dom-todo

- script: cargo docs-all
- publish: target/doc
  artifact: documentation

- task: ado-discord-webhook@1
  condition: $(eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    channelId: '610654874572554257'
    webhookKey: $(discord webhook key)
    messageType: 'embeds'
