strategy:
  matrix:
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
- script: rustup target add wasm32-unknown-unknown
- script: cargo install cargo-script

- script: cargo check-dom-lib
- script: cargo build-dom-hacking
- script: cargo build-dom-todo
