format_code_in_doc_comments = true
format_strings = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
# report_fixme = "Unnumbered"
# report_todo = "Unnumbered"
# struct_field_align_threshold = 20
use_field_init_shorthand = true
use_small_heuristics = "Max"
version = "Two"
wrap_comments = true
