[package]
name = "counter-moxie-dom-fn"
version = "0.1.0"
publish = false
description = "an example counter for moxie-dom"
edition = "2018"
license-file = "../../../../LICENSE-MIT"
repository = "https://github.com/anp/moxie.git"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = [ "cdylib" ]

[dependencies]
mox = { path = "../../../mox" }
moxie = { path = "../../.." }
moxie-dom = { path = "../../" }
wasm-bindgen = "0.2"
