load("@rules_rust//rust:defs.bzl", "rust_doc_test", "rust_proc_macro", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_proc_macro(
    name = "topo-macro",
    # FIXME translate this metadata somehow
    # description = "procedural macros for the topo crate"
    # readme = "../CHANGELOG.md"
    srcs = glob(["src/**/*.rs"]),
    edition = "2018",
    lint_config = "//:library_lints",
    version = "0.14.0-pre",
    deps = [
        "@crates//:quote",
        "@crates//:syn",
    ],
)

rust_test(
    name = "topo-macro_unit_tests",
    crate = "topo-macro",
)

rust_doc_test(
    name = "topo-macro_doc_tests",
    crate = "topo-macro",
)
