load("@rules_rust//rust:defs.bzl", "rust_proc_macro", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_proc_macro(
    name = "topo-macro",
    # FIXME translate this metadata somehow
    # description = "procedural macros for the topo crate"
    # readme = "../CHANGELOG.md"
    srcs = [
        "src/lib.rs",
    ],
    edition = "2018",
    lint_config = "//:library_lints",
    version = "0.10.0",
    deps = [
        "@crates//:quote",
        "@crates//:syn",
    ],
)

rust_test(
    name = "topo-macro_unit_tests",
    crate = "topo-macro",
)

test_suite(
    name = "tests",
    tests = [
        ":topo-macro_unit_tests",
    ],
)
