[package]
name = "dom-hacking"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0/MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
# moxie-dom = { path = "../../../" }
stdweb = "0.4.16"
wasm-bindgen = "0.2"
# wee_alloc = { version = "0.4.2", optional = true }

[profile.release]
opt-level = "s"
