[package]
name = "local-wasm-pack"
version = "0.1.0"
authors = ["Adam Perry <lol@anp.lol>"]
edition = "2018"
publish = false
description = "uses wasm-pack as a library to have cargo install it for us"

[[bin]]
path = "wasm-pack.rs"
name = "wasm-pack"

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
pretty_env_logger = "0.3"

[dependencies.wasm-pack]
version = "0.15.0"

[workspace]
