[package]
name = "code-sys"
version = "0.1.0-pre"
description = "Bindings to VSCode's extension API using wasm-bindgen."
categories = []
keywords = []
readme = "CHANGELOG.md"

# update here, update everywhere!
license = "MIT/Apache-2.0"
homepage = "https://moxie.rs"
repository = "https://github.com/anp/moxie.git"
authors = ["Adam Perry <lol@anp.lol>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"

[build-dependencies]
ts-bindgen = { path = "../../../../dom/ts-bindgen", version = "0.1.0" }