load("@rules_rust//rust:defs.bzl", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_test(
    name = "topo_simple_integration_test",
    srcs = [
        "simple.rs",
    ],
    deps = [
        "//topo",
    ],
)

rust_test(
    name = "topo_syn2_upgrade_failure",
    srcs = [
        "syn2_upgrade_failure.rs",
    ],
    deps = [
        "//topo",
    ],
)
