load("@rules_rust//rust:defs.bzl", "rust_doc_test", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "dyn-cache",
    # FIXME translate this metadata somehow
    # description = "Query cache indexed by type."
    # categories = ["caching", "rust-patterns"]
    # keywords = ["incremental", "memoize", "intern", "cache"]
    # readme = "CHANGELOG.md"
    srcs = [
        "src/cache_cell.rs",
        "src/definition.rs",
        "src/dep_node.rs",
        "src/lib.rs",
        "src/namespace.rs",
    ],
    edition = "2018",
    lint_config = "//:library_lints",
    proc_macro_deps = [
        "@crates//:paste",
    ],
    version = "0.12.2",
    deps = [
        "//illicit",
        "@crates//:downcast-rs",
        "@crates//:hash_hasher",
        "@crates//:hashbrown",
        "@crates//:parking_lot",
    ],
    # FIXME translate these features somehow
    # [features]
    # default = []
    # wasm-bindgen = [ "parking_lot/wasm-bindgen" ]
)

rust_doc_test(
    name = "dyn-cache_doc_tests",
    crate = "dyn-cache",
)

rust_test(
    name = "dyn-cache_unit_tests",
    crate = "dyn-cache",
    deps = [
        "@crates//:scopeguard",
    ],
)
