load("@rules_rust//rust:defs.bzl", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_test(
    name = "mox_dashes_integration_test",
    srcs = ["dashes.rs"],
    proc_macro_deps = [
        "//mox",
    ],
)

rust_test(
    name = "mox_derive_builder_integration_test",
    srcs = ["derive_builder.rs"],
    proc_macro_deps = [
        "//mox",
    ],
    deps = [
        "@crates//:derive_builder",
    ],
)

rust_test(
    name = "mox_simple_builder_integration_test",
    srcs = ["simple_builder.rs"],
    proc_macro_deps = [
        "//mox",
    ],
)

test_suite(
    name = "tests",
    tests = [
        ":mox_dashes_integration_test",
        ":mox_derive_builder_integration_test",
        ":mox_simple_builder_integration_test",
    ],
)
