[package]
name = "drivertest"
publish = false
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
edition = "2018"

[dependencies]
moxie = { path = "../../../", version = "0.1.1-alpha.0" }
moxie-dom = { path = "../../", version = "0.1.1-alpha.0", features = ["rsdom"] }
typed-html = "0.2.1"
wasm-bindgen = "0.2.51"
wasm-bindgen-test = "0.3"

[dependencies.web-sys]
version = "0.3.28"
features = [
    "Element",
    "Node",
]
