[package]
name = "drivertest"
publish = false
version = "0.1.0-pre"
authors = ["Adam Perry <lol@anp.lol>"]
edition = "2018"

[dependencies]
augdom = { path = "../../augdom", features = ["rsdom"] }
moxie = { path = "../../../" }
moxie-dom = { path = "../../", features = ["rsdom"] }
topo = { path = "../../../topo" }
wasm-bindgen = "0.2.51"
wasm-bindgen-test = "0.3"

[dependencies.web-sys]
version = "0.3.28"
features = [
    "Element",
    "Node",
    "HtmlElement",
]
