load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "moxie",
    # FIXME translate this metadata somehow
    # description = "Incremental runtime for interactive software."
    # categories = ["asynchronous", "caching", "concurrency", "gui", "rust-patterns"]
    # keywords = ["incremental", "memoize", "intern", "reactive"]
    # readme = "CHANGELOG.md"
    srcs = [
        "src/lib.rs",
        "src/runtime.rs",
        "src/runtime/context.rs",
        "src/runtime/runloop.rs",
        "src/runtime/var.rs",
        "src/testing.rs",
    ],
    edition = "2018",
    version = "0.7.1",
    deps = [
        "//dyn-cache",
        "//illicit",
        "//topo",
        "@crates//:futures",
        "@crates//:parking_lot",
        "@crates//:scopeguard",
        "@crates//:tracing",
    ],
    # FIXME translate features somehow
    # [features]
    # default = []
    # wasm-bindgen = [ "dyn-cache/wasm-bindgen", "parking_lot/wasm-bindgen", "topo/wasm-bindgen" ]
)

rust_test(
    name = "moxie_unit_tests",
    crate = "moxie",
    deps = [
        "@crates//:tracing-subscriber",
    ],
)

test_suite(
    name = "tests",
    tests = [
        ":moxie_unit_tests",
        "//moxie/benches",
        "//moxie/tests",
    ],
)
