[package]
name = "raf"
version = "0.1.0-pre"
edition = "2018"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "MIT/Apache-2.0"
description = "browser event loop scheduler using requestAnimationFrame"
repository = "https://github.com/anp/moxie"


[dependencies]
futures-preview = "0.3.0-alpha.18"
wasm-bindgen = "0.2.48"
web-sys = { version = "0.3.28", features = ["Window"] }
