load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "topo",
    # FIXME translate this metadata somehow
    # description = "Tools for incrementally computing repeated callgraphs."
    # categories = ["caching", "data-structures", "gui", "memory-management", "rust-patterns"]
    # keywords = ["cache", "memoize", "intern", "topology", "incremental"]
    # readme = "CHANGELOG.md"
    srcs = [
        "src/lib.rs",
        "src/slot.rs",
    ],
    edition = "2018",
    proc_macro_deps = [
        "//topo/macro:topo-macro",
    ],
    version = "0.13.2",
    deps = [
        "//dyn-cache",
        "//illicit",
        "@crates//:once_cell",
        "@crates//:parking_lot",
    ],
    # FIXME translate these features somehow
    # [features]
    # default = []
    # wasm-bindgen = [ "dyn-cache/wasm-bindgen", "parking_lot/wasm-bindgen" ]
)

rust_test(
    name = "topo_unit_tests",
    crate = "topo",
)

test_suite(
    name = "tests",
    tests = [
        ":topo_unit_tests",
        "//topo/benches",
        "//topo/macro:tests",
        "//topo/tests",
    ],
)
