env:
  RUSTFLAGS: -D warnings
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  ofl:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project-tools
    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-ofl-${{ hashFiles('ofl/Cargo.lock') }}-${{ hashFiles('.mise/config.toml') }}-3
        path: |
          ~/.cargo/git
          ~/.cargo/registry
          ofl/target/release
    - run: cargo build --release
      working-directory: ofl
    - run: cargo test --release
      working-directory: ofl
    - uses: actions/upload-artifact@v4
      with:
        name: ofl-${{ runner.os }}
        path: ofl/target/release/ofl*

  coverage:
    needs: ofl
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project-tools
    - uses: ./.github/actions/download-ofl

    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-coverage-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('.mise/config.toml') }}-3
        path: |
          ~/.cargo/git
          ~/.cargo/registry
          target

    - run: bin/ofl coverage collect test-core
    - run: bin/ofl coverage collect test-core-doc
    - run: bin/ofl coverage collect test-dom
    - run: bin/ofl coverage collect test-dom-doc
    - run: bin/ofl coverage report
    - run: bin/ofl coverage cleanup

    - uses: codecov/codecov-action@v5
      with:
        file: ./target/coverage/lcov.info

  dom:
    needs: ofl
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project-tools
    - uses: ./.github/actions/download-ofl

    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-dom-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('.mise/config.toml') }}-3
        path: |
          ~/.cargo/git
          ~/.cargo/registry
          target

    - run: cargo test-prettiest
    - run: cargo test-augdom
    - run: cargo test-dom-lib-browser
    - run: cargo test-dom-counter-fn
    - run: cargo test-dom-dom-builder
    - run: cargo test-dom-hacking
    - run: cargo test-dom-todo
    - run: cargo test-dom-drivertest

    # - run: cd dom/examples/todo/e2e; npm ci
    # - name: todomvc e2e tests
    #   run: cargo test-dom-todo-e2e --record
    #   env:
    #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  website:
    needs: ofl
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project-tools
    - uses: ./.github/actions/download-ofl

    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-website-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('.mise/config.toml') }}-3
        path: |
          ~/.cargo/git
          ~/.cargo/registry
          ofl/target/doc
          target

    - run: cargo build-dom-counter-fn
    - run: cargo build-dom-dom-builder
    - run: cargo build-dom-hacking
    - run: cargo build-dom-todo
    - run: cargo docs-all
    - run: cargo docs-ofl
    - run: bin/ofl website build target/website
    - uses: actions/upload-artifact@v4
      if: runner.os == 'Linux'
      with:
        name: website
        path: target/website

  fmt:
    needs: ofl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project-tools
    - uses: ./.github/actions/download-ofl
    - run: bin/ofl fmt --check

  clippy:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project-tools
    - run: cargo clippy-ofl
    - run: cargo clippy-core
    - run: cargo clippy-dom

  blocking-ci:
    name: blocking CI
    if: always()
    needs: [clippy, coverage, dom, fmt, ofl, website]
    runs-on: ubuntu-latest
    steps:
    - name: report CI results
      run: |
        echo "clippy: ${{ needs.clippy.result }}"
        echo "coverage: ${{ needs.coverage.result }}"
        echo "dom: ${{ needs.dom.result }}"
        echo "fmt: ${{ needs.fmt.result }}"
        echo "ofl: ${{ needs.ofl.result }}"
        echo "website: ${{ needs.website.result }}"
    - name: require successful CI
      run: |
        if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
          exit 1
        fi
        if [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
          exit 1
        fi
        if [[ "${{ contains(needs.*.result, 'skipped') }}" == "true" ]]; then
          exit 1
        fi

  publish:
    if: github.ref == 'refs/heads/main'
    needs: blocking-ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-project-tools
    - uses: ./.github/actions/download-ofl
    - uses: actions/download-artifact@v4
      with:
        name: website
        path: target/website
    - name: promote website to prod, ensure crates published
      run: |
        netlify deploy --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
        cargo login ${{ secrets.CARGO_API_TOKEN }}
        bin/ofl published
        git push origin --tags
